Repository React-Project-lab5/React-Project-lab5, pull requests merged in 2023-03, with the labels that each got.

#1 [setting] package-lock.json 수정
  package-lock.json
Labels: ⚙️ Setting

#2 [setting] 폴더 및 파일구조 스캐폴딩
  package-lock.json
  package.json
  src/App.modules.scss
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/index.css
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/styles/common/a11y.scss
  src/styles/common/base.scss
  src/styles/common/theme.scss
  tsconfig.json
Labels: ⚙️ Setting

#7 [feat] Modal Component 구현
  src/App.tsx
  src/assets/close.svg
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/main.tsx
  src/styles/common/animation.scss
  src/styles/common/base.scss
  src/styles/common/index.scss
  src/styles/common/nomalize.scss
  src/styles/common/reset.scss
Labels: 💻 Feature

#9 [feat] React-Router를 이용한 SPA 생성
  .eslintrc.cjs
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  package-lock.json
  package.json
  public/vite.svg
  src/App.modules.scss
  src/App.tsx
  src/components/Button/Button.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/LogoIconandText/LogoIconandText.module.scss
  src/components/LogoIconandText/LogoIconandText.tsx
  src/components/LogoText/LogoText.module.scss
  src/components/LogoText/LogoText.tsx
  src/components/Nav/Nav.module.scss
  src/components/Nav/Nav.tsx
  src/components/index.tsx
  src/pages/Chat/Chat.module.scss
  src/pages/Chat/Chat.tsx
  src/pages/Home/Home.tsx
  src/pages/MainPage/MainPage.module.scss
  src/pages/MainPage/MainPage.tsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFound/NotFound.module.scss
  src/pages/NotFound/NotFound.tsx
  src/pages/Recommend/Recommend.module.scss
  src/pages/Recommend/Recommend.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/common/animaion.scss
  src/styles/common/index.scss
  src/styles/common/nomalize.scss
  src/styles/common/reset.scss
  src/styles/common/theme.scss
  vite.config.ts
Labels: 💻 Feature

#19 [feat] Banner 컴포넌트 구현
  package-lock.json
  package.json
  public/assets/avatar_1.svg
  public/assets/avatar_2.svg
  public/assets/avatar_3.svg
  public/assets/banner_1.svg
  public/assets/banner_2.svg
  public/assets/banner_3.svg
  public/assets/blog.svg
  public/assets/close.svg
  public/assets/faceBook.svg
  public/assets/googleLogo.svg
  public/assets/homeBanner_1.svg
  public/assets/homeBanner_2.svg
  public/assets/homeBanner_3.svg
  public/assets/instagram.svg
  public/assets/kakaoLogo.svg
  public/assets/logo.svg
  public/assets/naverPost.svg
  public/assets/youtube.svg
  src/App.tsx
  src/components/Banner/Banner.modules.scss
  src/components/Banner/Banner.tsx
  src/components/LogoIconandText/LogoIconandText.tsx
  src/components/Modal/Modal.tsx
  src/components/index.tsx
Labels: 💻 Feature

#20 [feat] Button 컴포넌트 구현
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
Labels: 💻 Feature

#21 [feat] Input 상자 UI 구현
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
Labels: 💻 Feature, 🔨 Refactor

#24 [feat] Input(with Label) 컴포넌트 구현
  src/components/Button/Button.tsx
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
Labels: 💻 Feature

#27 [feat] InputSelector UI구현 완성 - useState로 구현
  src/components/InputSelector/InputSelector.module.scss
  src/components/InputSelector/InputSelector.tsx
Labels: 💻 Feature

#28 [style] 채팅 페이지 UI 구현
  package-lock.json
  package.json
  public/assets/chatAvatars.svg
  public/assets/chatImagePlaceholder.svg
  public/assets/chatMessage.svg
  public/assets/chatPaperPlane.svg
  src/App.tsx
  src/components/ChatDialog/Chatting/Chatting.module.scss
  src/components/ChatDialog/Chatting/Chatting.tsx
  src/components/ChatDialog/ChattingInput/ChattingInput.module.scss
  src/components/ChatDialog/ChattingInput/ChattingInput.tsx
  src/components/ChatDialog/Chattings/Chattings.module.scss
  src/components/ChatDialog/Chattings/Chattings.tsx
  src/components/ChatDialog/Message/Message.module.scss
  src/components/ChatDialog/Message/Message.tsx
  src/components/ChatDialog/Messages/Messages.module.scss
  src/components/ChatDialog/Messages/Messages.tsx
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/ChatDialog/Search/Search.module.scss
  src/components/ChatDialog/Search/Search.tsx
  src/components/ChatDialog/Sidebar/Sidebar.module.scss
  src/components/ChatDialog/Sidebar/Sidebar.tsx
  src/components/ChatDialog/index.ts
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/pages/Chat/Chat.module.scss
  src/pages/Chat/Chat.tsx
  vite.config.ts
Labels: 🎨Html&Css

#29 [feat] Potal을 이용한 Modal 창 UI, 닫기기능 구현
  index.html
  src/App.tsx
  src/components/Banner/Banner.module.scss
  src/components/Banner/Banner.modules.scss
  src/components/Banner/Banner.tsx
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.module.scss
  src/components/Input/Input.tsx
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalPotal.tsx
  src/components/Modal/ModalTotal.tsx
  src/components/index.tsx
  src/pages/MainPage/MainPage.tsx
Labels: 💻 Feature

#33 [feat] Card UI Component 구현
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/pages/Chat/Chat.module.scss
Labels: 💻 Feature

#34 [chore] Button, Input 컴포넌트 코드 수정
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/components/Button/index.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/components/index.tsx
Labels: 🔨 Refactor

#37 [feat] 모임만들기 팝업창 - 지도 api 연결
  index.html
  package-lock.json
  package.json
  src/components/InputSelector/InputSelector.module.scss
  src/components/InputSelector/InputSelector.tsx
  src/components/LogoText/LogoText.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalPotal.tsx
  src/components/Modal/ModalTotal.tsx
  src/utils/MapContainer.tsx
Labels: 🎨Html&Css

#41 메인페이지 - UI 구현 완성
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Card/Meeting.tsx
  src/components/Card/index.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/components/InputSelector/InputSelector.tsx
  src/components/index.tsx
  src/pages/MainPage/MainPage.module.scss
  src/pages/MainPage/MainPage.tsx
  src/styles/common/index.scss
  src/styles/common/mediaQuery.scss
Labels: 💻 Feature, ⚙️ Setting, 🔨 Refactor, 🎨Html&Css

#43 [style] MainPage Card 반응형 구현
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/pages/MainPage/MainPage.module.scss
Labels: 🔨 Refactor, 🎨Html&Css

#44 [feat] 마이페이지 초기 UI 구현
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 🎨Html&Css

#45 [feat] firebase Card create, read 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchForm.tsx
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ShowMeetings.tsx
  src/components/index.tsx
  src/firebase/README.md
  src/firebase/app.ts
  src/firebase/auth/README.md
  src/firebase/auth/index.js
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignIn.js
  src/firebase/auth/useSignOut.js
  src/firebase/auth/useSignUp.js
  src/firebase/firestore/README.md
  src/firebase/firestore/index.js
  src/firebase/firestore/useCreateAuthUser.js
  src/firebase/firestore/useCreateData.js
  src/firebase/firestore/useDataState.js
  src/firebase/firestore/useDeleteData.js
  src/firebase/firestore/useReadData.js
  src/firebase/firestore/useUpdateData.js
  src/firebase/firestore/useWriteBatchData.js
  src/firebase/storage/README.md
  src/firebase/storage/index.ts
  src/firebase/storage/useDeleteFile.ts
  src/firebase/storage/useDownloadURL.ts
  src/firebase/storage/useUploadFile.ts
  src/pages/MainPage/MainPage.tsx
  src/styles/common/mediaQuery.scss
  src/utils/MapContainer.tsx
  src/utils/mediaQuery.ts
Labels: 💻 Feature

#53 메인페이지 - Map API 클릭시 Marker 표시하기
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/utils/MapContainer.module.scss
  src/utils/MapContainer.tsx
Labels: 💻 Feature, 🔨 Refactor, 🎨Html&Css

#54 [style] 로그인 팝업창 UI 구현
  package-lock.json
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/components/Card/Card.stories.ts
  src/components/ChatDialog/Chatting/Chatting.module.scss
  src/components/ChatDialog/Chatting/Chatting.tsx
  src/components/ChatDialog/ChattingInput/ChattingInput.module.scss
  src/components/ChatDialog/ChattingInput/ChattingInput.tsx
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/ChatDialog/Search/Search.tsx
  src/components/ChatDialog/Sidebar/Sidebar.module.scss
  src/components/Input/Input.tsx
  src/components/SignIn/SignIn.module.scss
  src/components/SignIn/SignIn.tsx
  src/styles/common/index.scss
Labels: 💻 Feature, 🎨Html&Css

#55 [feat] 모임만들기 card : firebase DB와 연동(create, read)
  src/components/Card/Card.tsx
  src/components/Card/Meeting.tsx
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ShowMeetings.tsx
  src/components/index.ts
  src/firebase/app.ts
  src/firebase/firestore/index.ts
  src/main.tsx
  src/pages/MainPage/MainPage.module.scss
  src/pages/MainPage/MainPage.tsx
  src/states/cardDataState.ts
  src/utils/mediaQuery.ts
Labels: 💻 Feature

#58 [style] 마이페이지 UI 구현 및 Input 컴포넌트 type prop 추가
  src/components/Input/Input.tsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 🔨 Refactor, 🎨Html&Css

#60 [style] 회원가입 UI 구현
  src/components/Input/Input.module.scss
  src/components/Input/Input.tsx
  src/components/Modal/Modal.tsx
  src/components/SignUP/SignUp.module.scss
  src/components/SignUP/SignUp.tsx
  src/firebase/app.ts
  src/firebase/auth/index.ts
  src/firebase/auth/useAuthState.ts
  src/firebase/auth/useSignIn.ts
  src/firebase/auth/useSignOut.ts
  src/firebase/auth/useSignUp.ts
  src/firebase/firestore/useCreateAuthUser.ts
  src/firebase/firestore/useCreateData.ts
  src/firebase/firestore/useDataState.ts
  src/firebase/firestore/useDeleteData.ts
  src/firebase/firestore/useReadData.ts
  src/firebase/firestore/useUpdateData.ts
  src/firebase/firestore/useWriteBatchData.ts
  src/firebase/storage/index.ts
  src/firebase/storage/useDeleteFile.ts
  src/firebase/storage/useDownloadURL.ts
  src/firebase/storage/useUploadFile.ts
Labels: 🎨Html&Css

#63 [style] NotFound Page UI 구현
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/ChatDialog/Sidebar/Sidebar.module.scss
  src/pages/NotFound/NotFound.module.scss
  src/pages/NotFound/NotFound.tsx
Labels: 🎨Html&Css

#64 [feat] 모바일 반응형 헤더 및 메뉴바 구현
  public/assets/hamburger.svg
  src/components/Button/Button.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchForm.tsx
  src/components/InputSelector/InputSelector.module.scss
  src/components/LogoIconandText/LogoIconandText.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Nav/Nav.module.scss
  src/components/Nav/Nav.tsx
  src/states/isActive.ts
Labels: 💻 Feature, 🎨Html&Css

#73 [refactor] 라우터 리펙토링
  src/App.tsx
  src/components/Input/Input.tsx
  src/hooks/useDocumentTitle.ts
  src/pages/Layout/Layout.tsx
Labels: 🔨 Refactor

#81 [style] Footer Component
  public/assets/blog.svg
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
  src/components/SocialIconGroup/SocialIconGroup.module.scss
  src/components/SocialIconGroup/SocialIconGroup.tsx
  src/components/index.ts
  src/styles/common/MediaQuery.scss
Labels: 🎨Html&Css

#82 [feat] 마이페이지 ProfileImage 컴포넌트 추가
  public/assets/defaultImage.svg
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/ProfileImage/ProfileImage.tsx
  src/components/index.ts
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature

#86 [style] 메인 페이지 반응형 수정
  public/assets/search.svg
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Input/Input.module.scss
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowMeetings.tsx
  src/pages/MainPage/MainPage.module.scss
  src/pages/MainPage/MainPage.tsx
  src/utils/MapContainer.module.scss
Labels: 🔨 Refactor, 🎨Html&Css

#87 [chore] 컴포넌트 수정 (ButtonGoogle, ButtonKakao, Input)
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/components/Input/Input.tsx
Labels: 🔨 Refactor

#89 [style] Home UI 구현
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
Labels: 🎨Html&Css

#93 [feat] 로그인 & 회원가입 기능 구현
  src/components/Button/ButtonGoogle.tsx
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignUP/SignUp.module.scss
  src/components/SignUP/SignUp.tsx
  src/context/AuthContext.tsx
  src/main.tsx
  src/pages/Chat/Chat.module.scss
Labels: 💻 Feature

#94 [feat] Card - timeStamp 내림차순으로 정렬 및 타입 재설정
  src/@types/global.d.ts
  src/components/Card/Card.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchForm.tsx
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/Form.tsx
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowMeetings.tsx
  src/pages/MainPage/MainPage.tsx
Labels: 💻 Feature, 🔨 Refactor, 📙 enhancement

#98 [style] map api 수정 및 inputSelector 주소 추가
  index.html
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/ModalTotal.tsx
  src/utils/MapContainer.tsx
Labels: 🎨Html&Css

#99 [style] logoText 추가 및 font-size 단위 수정
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.tsx
Labels: 🎨Html&Css

#101 [feat] Card firestore로부터 Read 후, 모달창에 정보 띄우기
  package-lock.json
  package.json
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowMeetings.tsx
Labels: 💻 Feature, 🔨 Refactor, 🎨Html&Css

#104 [feat] 홈(첫 화면 페이지) - 스와이퍼 기능 및 UI 구현 완료
  src/components/Banner/Banner.module.scss
  src/components/Banner/HomeBanner.tsx
  src/components/Banner/index.tsx
  src/components/Input/Input.module.scss
  src/components/Modal/Modal.module.scss
  src/components/index.ts
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
Labels: 💻 Feature, 🎨Html&Css

#105 [feat] Card 클릭시 팝업창에 해당 데이터 지도 정보 불러오기
  src/components/Input/Input.tsx
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/pages/MainPage/MainPage.tsx
  src/states/addressState.ts
  src/states/mapState.ts
  src/states/readingMap.ts
  src/utils/MapContainer.tsx
  src/utils/MapReading.tsx
Labels: 💻 Feature

#107 [feat] 로그인된 사용자 정보 찾기
  src/App.tsx
  src/components/Button/Button.tsx
  src/components/ChatDialog/Chatting/Chatting.tsx
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/ChatDialog/Search/Search.tsx
  src/components/ChatDialog/SendMessage/SendMessage.module.scss
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/components/ChatDialog/index.ts
  src/styles/common/animaion.scss
Labels: 💻 Feature

#110 [feat] 채팅 창에 메세지입력시 메세지 생성
  index.html
  src/components/ChatDialog/Chatting/Chatting.tsx
  src/components/ChatDialog/Message/Message.module.scss
  src/components/ChatDialog/Message/Message.tsx
  src/components/ChatDialog/Messages/Messages.tsx
  src/components/ChatDialog/Search/Search.tsx
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignUP/SignUp.tsx
  src/pages/Home/Home.tsx
  src/pages/Recommend/Recommend.tsx
Labels: 💻 Feature

#115 [feat] ProfileImage 이미지 불러오기 구현
  src/components/ProfileImage/ProfileImage.tsx
Labels: 💻 Feature

#116 [feat] 채팅 입력시 스크롤바 최신순으로 조정
  src/App.tsx
  src/components/ChatDialog/Messages/Messages.tsx
  src/components/ChatDialog/SendMessage/SendMessage.module.scss
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/context/AuthContext.tsx
  src/pages/Home/Home.tsx
  src/pages/Layout/Layout.tsx
Labels: 🐛 BugFix, 💻 Feature

#118 [feat] fireStore 삭제 기능 & 화면 렌더링 동기화 구현
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowCard.tsx
  src/components/Modal/ShowMeetings.tsx
  src/pages/MainPage/MainPage.tsx
  src/states/deleteUsers.ts
  src/states/usersState.ts
  src/utils/MapReading.tsx
Labels: 🐛 BugFix, 💻 Feature

#120 [fix] 지도 마커 미이동시 에러났던거 해결
  src/components/Modal/ShowCard.tsx
  src/utils/MapContainer.tsx
Labels: 🐛 BugFix, 🔨 Refactor

#123 [fix] 마이페이지 새로고침 후 이미지가 정상적으로 다운로드 안되던 문제 해결
  src/components/ProfileImage/ProfileImage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 🐛 BugFix, 💻 Feature

#124 [feat] fireStore에서 채팅 이미지 데이터 받아오기
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/Modal/ReadMeetings.tsx
  src/context/AuthContext.tsx
Labels: 💻 Feature

#125 [feat] nav 프로필 이미지 불러오기 구현
  src/components/ChatDialog/Navbar/Navbar.tsx
Labels: 💻 Feature

#129 [feat] 마이페이지 user 데이터 input에 불러오기 / 로그아웃 기능 구현
  src/components/Input/Input.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/components/SignUP/SignUp.tsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 🐛 BugFix, 💻 Feature, 🔨 Refactor

#134 [feat] 마이페이지 currentUser와 일부 연동 및 회원탈퇴 구현
  src/components/ProfileImage/ProfileImage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature, 🔨 Refactor

#137 [feat] firestore 연동하여 사용자 재인증 기능 구현
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/SignUP/SignUp.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature, 🔨 Refactor

#139 [feat] 홈 (첫 화면 페이지) - 로그인, 회원가입 버튼 클릭시 모달창 띄우기
  index.html
  src/components/Banner/Banner.module.scss
  src/components/Banner/HomeBanner.tsx
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/components/LogoText/LogoText.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/SignIn/SignIn.module.scss
  src/components/SignIn/SignIn.tsx
  src/components/SignUP/SignUp.module.scss
  src/components/SignUP/SignUp.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
  src/states/signState.ts
Labels: 💻 Feature, 🎨Html&Css

#140 [feat] 채팅 - 이미지 업로드 기능 구현
  public/assets/defaultAvatars.svg
  src/components/ChatDialog/Chatting/Chatting.module.scss
  src/components/ChatDialog/Chatting/Chatting.tsx
  src/components/ChatDialog/Message/Message.module.scss
  src/components/ChatDialog/Message/Message.tsx
  src/components/ChatDialog/Navbar/Navbar.module.scss
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/ChatDialog/Search/Search.tsx
  src/components/ChatDialog/SendMessage/SendMessage.module.scss
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/components/ChatDialog/Sidebar/Sidebar.module.scss
  src/components/ChatDialog/Sidebar/Sidebar.tsx
  src/components/SignIn/SignIn.tsx
  src/pages/Chat/Chat.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/Recommend/Recommend.tsx
  src/states/authImgState.ts
Labels: 💻 Feature

#142 [feat] 구글 로그인 사용자 정보 불러오기 구현
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/ProfileImage/ProfileImage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature

#144 [feat] 벨리데이션 검사 함수
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/utils/validation.ts
Labels: 💻 Feature

#145 [feat] 모임만들기 Card - search filter 기능 구현
  src/components/Header/Header.module.scss
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/components/InputSelector/InputSelector.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/lazyMinLoadTime.tsx
  src/pages/MyPage/MyPage.tsx
  src/utils/MapContainer.tsx
Labels: 💻 Feature, 🔨 Refactor

#149 [chore] 구글, 카카오 버튼 & MyPage SCSS 리팩토링
  src/components/Button/ButtonGoogle.tsx
  src/components/Button/ButtonKakao.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.module.scss
Labels: 🔨 Refactor, 🎨Html&Css

#153 [feat] 추천 페이지 구현
  public/assets/banner_3.svg
  src/components/FoodList/FoodList.module.scss
  src/components/FoodList/FoodList.tsx
  src/components/Pagination/Pagination.module.scss
  src/components/Pagination/Pagination.tsx
  src/hooks/useDocumentTitle.ts
  src/pages/Recommend/Recommend.tsx
Labels: 💻 Feature, 🎨Html&Css

#154 [chore] 프로필 이미지 defaultAvatar로 통일
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/ProfileImage/ProfileImage.tsx
Labels: 🔨 Refactor

#155 [feat] 로그인한 사용자 card 정보에 사진, 이름 띄우기 및 검색 조건 기능 추가
  src/@recoil/readingMap.ts
  src/@recoil/usersState.ts
  src/components/Card/Card.module.scss
  src/components/Card/Meeting.tsx
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowCard.tsx
  src/components/Modal/ShowMeetings.tsx
  src/components/Modal/UserContainer.tsx
  src/components/SignUP/SignUp.tsx
  src/pages/MainPage/MainPage.tsx
  src/utils/MapContainer.tsx
  src/utils/MapReading.tsx
Labels: 💻 Feature, 🔨 Refactor

#158 [feat] 마이페이지 debounce 함수 직접 제작 및 메인페이지 코드 수정
  src/pages/MainPage/MainPage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature, 🔨 Refactor

#162 [style] Home 반응형 및 이미지 교체
  public/assets/homeBanner_1.svg
  public/assets/homeBanner_2.svg
  public/assets/homeBanner_3.svg
  src/@recoil/signState.ts
  src/components/Banner/HomeBanner.tsx
  src/pages/Home/Home.module.scss
  src/pages/Home/Home.tsx
Labels: 🎨Html&Css

#160 [feat] 마이페이지 debounce 적용 및 isLoading 상태 관리 추가
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature, 🔨 Refactor

#163 [feat] 모임만들기 팝업창 참여하기 버튼 생성
  src/@recoil/usersState.ts
  src/components/Modal/Modal.module.scss
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowCard.tsx
  src/components/Modal/UserContainer.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/utils/MapContainer.module.scss
Labels: 💻 Feature, 🔨 Refactor, 🎨Html&Css

#165 [feat] tabIndex를 이용한 focus 접근성 구현
  src/components/Button/Button.module.scss
  src/components/Card/Card.tsx
  src/components/Input/Input.module.scss
  src/components/Input/SearchForm.tsx
  src/components/InputSelector/InputSelector.module.scss
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalPotal.tsx
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/Modal/ShowMeetings.tsx
Labels: 💻 Feature, 🔨 Refactor, 🎨Html&Css

#176 [chore] MyPage, ProfileImage에 TabIndex 추가
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/ProfileImage/ProfileImage.tsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 🔨 Refactor, 🎨Html&Css

#175 [chore] 코드 정리
  package-lock.json
  package.json
  src/components/LogoIconandText/LogoIconandText.tsx
  src/components/Modal/ReadMeetings.tsx
Labels: ⚙️ Setting, 🔨 Refactor

#177 [chore] 타입 설정 정리
  package-lock.json
  package.json
  src/@types/global.d.ts
  src/components/Button/ButtonKakao.tsx
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/components/Input/SearchForm.tsx
  src/components/Modal/ShowCard.tsx
  src/pages/MyPage/MyPage.tsx
Labels: ⚙️ Setting, 🔨 Refactor

#178 [chore] 공지사항 목록 링크로 변경
  src/components/Footer/Footer.tsx
Labels: 🎨Html&Css

#179 [chore] 코드 리펙토링
  README.md
  public/preview/userFlow.png
  public/preview/wireFrame.png
  src/@recoil/pageState.ts
  src/components/ChatDialog/Chatting/Chatting.module.scss
  src/components/ChatDialog/Navbar/Navbar.tsx
  src/components/ChatDialog/SendMessage/SendMessage.module.scss
  src/components/ChatDialog/SendMessage/SendMessage.tsx
  src/components/Modal/ModalTotal.tsx
  src/components/Modal/ReadMeetings.tsx
  src/components/SignIn/SignIn.tsx
  src/components/SignUP/SignUp.tsx
  src/firebase/README.md
  src/firebase/auth/index.ts
  src/pages/Chat/Chat.tsx
  src/pages/Recommend/Recommend.tsx
  src/utils/MapContainer/MapContainer.module.scss
  src/utils/MapContainer/MapContainer.tsx
Labels: 💻 Feature, 👓 a11y

#182 [feat] 마이페이지 vaildation 추가 및 SignUp 컴포넌트 수정
  src/components/SignUP/SignUp.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 💻 Feature, 🔨 Refactor

#184 [chore] 마이페이지, 카카오 로그인 버튼 코드 리팩토링
  src/@types/global.d.ts
  src/components/Button/ButtonKakao.tsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/MyPage.tsx
Labels: 🔨 Refactor, 🎨Html&Css

#185 [feat] 카카오 유저 프로필 이미지 수정 접근 제한 구현
  src/components/ProfileImage/ProfileImage.tsx
Labels: 💻 Feature, 🔨 Refactor

#187 [feat] 이미지 깨지는 문제 해결
  src/components/Input/SearchForm.tsx
  src/components/Modal/ModalPotal.tsx
  src/components/Modal/ShowCard.tsx
  src/components/Nav/Nav.tsx
Labels: 🔨 Refactor

#190 [chore] Recommend & SearchForm 코드 리팩토링
  src/components/Input/SearchForm.module.scss
  src/components/Input/SearchForm.tsx
  src/components/Input/SearchFrom.module.scss
  src/pages/Recommend/Recommend.module.scss
  src/pages/Recommend/Recommend.tsx
Labels: 🔨 Refactor

#192 [setting] firebase hosting 관련 파일 추가
  .firebase/hosting.ZGlzdA.cache
  .firebaserc
  firebase.json
Labels: 📒 Deploy

#193 [setting] firebase hosting 관련 추가 Merge
  .firebase/hosting.ZGlzdA.cache
  .firebaserc
  firebase.json
Labels: 📒 Deploy, ⚙️ Setting
